export const GET_INVITE_REQUESTED = 'GET_INVITE_REQUESTED'
export const GET_INVITE_REJECTED = 'GET_INVITE_REJECTED'
export const GET_INVITE_FULFILLED = 'GET_INVITE_FULFILLED'

export const ADD_TO_INVITE_REQUESTED = 'ADD_TO_INVITE_REQUESTED'
export const ADD_TO_INVITE_REJECTED = 'ADD_TO_INVITE_REJECTED'
export const ADD_TO_INVITE_FULFILLED = 'ADD_TO_INVITE_FULFILLED'

export const GUEST_ADDED = 'GUEST_ADDED'
